name: Dev CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Get .env from S3
        run: aws s3 cp s3://sola-secrets/sola-auth-service/.env .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.8.0
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-dev-buildx-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-dev-buildx-

      - name: Log in to Vultr Container Registry
        run: docker login https://ewr.vultrcr.com/develop1 -u ${{ secrets.VULTR_REGISTRY_USER }} -p ${{ secrets.VULTR_REGISTRY_PASSWORD }}

      - name: Build, tag, and push image to Registry
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --platform linux/amd64 \
                              --cache-from=type=local,src=/tmp/.buildx-cache \
                              --cache-to=type=local,dest=/tmp/.buildx-cache \
                              --tag ewr.vultrcr.com/develop1/sola-auth-service:latest \
                              --push .
          echo "image=ewr.vultrcr.com/develop1/sola-auth-service:latest" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VULTR_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VULTR_INSTANCE_IP }} >> ~/.ssh/known_hosts

      - name: SSH into Vultr Docker Instance and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.VULTR_INSTANCE_IP }} << 'EOF'
            docker login https://ewr.vultrcr.com/develop1 -u ${{ secrets.VULTR_REGISTRY_USER }} -p ${{ secrets.VULTR_REGISTRY_PASSWORD }}

            docker pull ewr.vultrcr.com/develop1/sola-auth-service:latest

            docker stop sola-auth-service || true
            docker rm sola-auth-service || true

            docker run -d --name sola-auth-service -p 8000:8000 ewr.vultrcr.com/develop1/sola-auth-service:latest
          EOF
